### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by patric-eberle** [valantic/webpack-dependency-hint#1]
- [x] Please move this line below all `const` definitions.

https://github.com/valantic/webpack-dependency-hint/blob/93089bcc7f7459aea88dc2014c96c0e88a08aff8/index.js#L5

- [x] You need to define this packages as `dependencies`. Else they will not be installed by default.

https://github.com/valantic/webpack-dependency-hint/blob/93089bcc7f7459aea88dc2014c96c0e88a08aff8/package.json#L6

- [x] Did you try to show this, when the webpack process starts? I think it would show up more prominent.

https://github.com/valantic/webpack-dependency-hint/blob/93089bcc7f7459aea88dc2014c96c0e88a08aff8/index.js#L30

- [x] Please check if your package is also compatible with webpack 5.

**Comment by janwidmer** [comment]
Please also test it with webpack 5 in vue-template :-)

**Comment by claudio147** [comment]
@janwidmer @patric-eberle Works well with webpack 5
